import {validateAnalysis} from './compute/analysis-schema.js';
import {validateTeaching,applyBindings} from './teaching.js';
import {validateControls} from './authoring.js';
import {objectKinds,connectionKinds,fieldKinds} from './components.js';
export const reservedNames=new Set(['t','x','y','vx','vy','m','x0','y0','vx0','vy0','pi','e','sin','cos','tan','sqrt','abs','min','max','pow','exp','log','floor','ceil']);
const identifier=/^[A-Za-z][A-Za-z0-9_]{0,39}$/;
function assert(ok,message){if(!ok)throw new Error(message);}
function str(v,label,max=500,nonempty=false){assert(typeof v==='string'&&v.length<=max&&(!nonempty||v.trim().length>0),`Проверьте ${label}`);}
function num(v,label,min=-1e7,max=1e7){assert(typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max,`Проверьте ${label}`);}
export function validateModel(input){assert(input&&typeof input==='object','Некорректный файл модели');const m=structuredClone(input);assert(m.version===1,'Версия файла модели не поддерживается');str(m.title,'название',120,true);for(const k of ['description','notes','lesson'])str(m[k],k==='lesson'?'название урока':k==='notes'?'пояснение':'описание',k==='lesson'?100:4000);assert(['8','10','all'].includes(m.grade),'Проверьте класс');assert(['physics','math'].includes(m.subject),'Проверьте предмет');
 validateAnalysis(m.analysis);validateTeaching(m);applyBindings(m);if(m.topic!==undefined)str(m.topic,'тему',80);if(m.kind==='html'){assert(m.analysis===undefined,'Анализ данных доступен в конструкторе');if(m.initialControls!==undefined)validateControls(m.initialControls);str(m.html,'HTML модели',180000,true);assert(/<html[\s>]/i.test(m.html),'Нужен самостоятельный HTML-документ');if(m.previewTheme!==undefined)assert(['force','belt','slope','collision','glass','cloth','boiling','humidity','trapezoid','rectangle','html'].includes(m.previewTheme),'Проверьте тему превью');return {...emptyModel(),...m,bodies:[],parameters:[],quantities:[],graphs:[]};}
 assert(m.kind===undefined||m.kind==='native','Неизвестный тип модели');num(m.duration,'длительность',.1,300);num(m.dt,'шаг',.001,.05);assert(m.scene&&typeof m.scene.grid==='boolean','Проверьте сцену');for(const k of ['minX','maxX','minY','maxY'])num(m.scene[k],'диапазон осей');assert(m.scene.maxX>m.scene.minX&&m.scene.maxY>m.scene.minY,'Максимум оси должен быть больше минимума');
 m.connections??=[];m.fields??=[];
 if(m.scene.camera!==undefined){for(const k of ['x','y'])num(m.scene.camera?.[k],'положение камеры');num(m.scene.camera.zoom,'масштаб камеры',.1,30);}
 for(const [name,max]of [['parameters',24],['bodies',60],['quantities',20],['graphs',4],['connections',80],['fields',12]])assert(Array.isArray(m[name])&&m[name].length<=max,`Проверьте список ${name}`);
 const ids=new Set();for(const item of [...m.parameters,...m.bodies,...m.quantities,...m.connections,...m.fields]){assert(identifier.test(item.id),`Имя «${item.id}»: используйте латинские буквы и цифры`);assert(!ids.has(item.id)&&!reservedNames.has(item.id),`Имя «${item.id}» повторяется или зарезервировано`);ids.add(item.id);}
 for(const p of m.parameters){str(p.label,'подпись параметра',80,true);str(p.unit,'единицу',30);for(const k of ['value','min','max'])num(p[k],'параметр',-1e30,1e30);assert(p.max>p.min&&p.value>=p.min&&p.value<=p.max,`Проверьте диапазон «${p.label}»`);}
 for(const b of m.bodies){str(b.name,'название объекта',80,true);assert(objectKinds.some(k=>k[0]===b.shape),'Проверьте вид объекта');assert(/^#[0-9a-fA-F]{6}$/.test(b.color),'Проверьте цвет');assert(['fixed','force','formula'].includes(b.motion),'Проверьте поведение');for(const k of ['x','y','vx','vy'])num(b[k],'координату или скорость');num(b.mass,'массу',.000001,1e30);if(b.gravityRadius!==undefined){num(b.gravityRadius,'радиус гравитационного источника',0,1e7);assert(b.gravityRadius===0||b.motion==='fixed','Однородный шар должен быть неподвижным. Для движущихся источников используйте радиус 0.');};num(b.size,'размер',.02,1000);for(const k of ['width','height'])if(b[k]!==undefined)num(b[k],'размер объекта',.02,2000);if(b.angle!==undefined)num(b.angle,'угол рисунка',-36000,36000);if(b.charge!==undefined)num(b.charge,'заряд');if(b.gravityEnabled!==undefined)assert(typeof b.gravityEnabled==='boolean','Проверьте создание гравитационного поля');if(b.fieldEnabled!==undefined)assert(typeof b.fieldEnabled==='boolean','Проверьте создание поля частицы');for(const k of ['fx','fy','xFormula','yFormula'])str(b[k],'формулу',500,true);assert(typeof b.trail==='boolean'&&typeof b.vector==='boolean','Проверьте отображение');for(const suffix of ['x','y','vx','vy','m','q','R','gravity'])assert(!ids.has(`${b.id}_${suffix}`),'Имя величины совпадает с координатами объекта');}
 const bodyIds=new Set(m.bodies.map(b=>b.id));
 for(const c of m.connections){str(c.name,'название связи',80,true);assert(connectionKinds.some(k=>k[0]===c.type),'Проверьте тип связи');assert(bodyIds.has(c.a)&&bodyIds.has(c.b)&&c.a!==c.b,`Связь «${c.name}»: выберите два разных объекта`);num(c.length,'длину связи',.02,1e5);for(const k of ['stiffness','damping'])str(c[k],'формулу связи',500,true);assert(typeof c.enabled==='boolean'&&typeof c.show==='boolean','Проверьте отображение связи');assert(/^#[0-9a-fA-F]{6}$/.test(c.color),'Проверьте цвет связи');}
 for(const f of m.fields){f.all??=f.targets?.length===0;assert(typeof f.all==='boolean','Проверьте область действия поля');str(f.name,'название поля',80,true);assert(fieldKinds.some(k=>k[0]===f.type),'Проверьте тип поля');assert(typeof f.enabled==='boolean'&&typeof f.show==='boolean','Проверьте отображение поля');assert(Array.isArray(f.targets)&&f.targets.length<=60&&new Set(f.targets).size===f.targets.length&&f.targets.every(id=>bodyIds.has(id)),'Проверьте объекты поля');assert(/^#[0-9a-fA-F]{6}$/.test(f.color),'Проверьте цвет поля');for(const k of ['gx','gy','ex','ey','bz','drag'])str(f[k],'формулу поля',500,true);if(f.type==='magnetic-gradient')for(const k of ['b0','bxGradient','byGradient','originX','originY'])str(f[k],'формулу неоднородного поля',500,true);}
 if(m.scene.fieldLayers!==undefined){assert(m.scene.fieldLayers&&typeof m.scene.fieldLayers==='object'&&!Array.isArray(m.scene.fieldLayers),'Проверьте слои поля');for(const [key,value]of Object.entries(m.scene.fieldLayers))assert(['electric','gravity','magnetic'].includes(key)&&typeof value==='boolean','Проверьте слой поля');}
 for(const g of m.graphs){if(g.autoScale!==undefined)assert(typeof g.autoScale==='boolean','Проверьте масштаб графика');if(g.autoScale===false){num(g.minY,'минимум графика',-1e100,1e100);num(g.maxY,'максимум графика',-1e100,1e100);assert(g.maxY>g.minY,'Максимум графика должен быть больше минимума');}}
 for(const q of [...m.quantities,...m.graphs]){assert(identifier.test(q.id),'Проверьте имя величины или графика');str(q.label,'подпись',80,true);str(q.unit,'единицу',30);str(q.expression,'формулу',500,true);}return m;
}
export function emptyModel(){return {version:1,title:'Новая модель',description:'',lesson:'',topic:'',grade:'all',subject:'physics',notes:'',duration:15,dt:.01,scene:{minX:-2,maxX:12,minY:-2,maxY:8,grid:true},parameters:[],bodies:[],connections:[],fields:[],quantities:[],graphs:[]};}
export function newBody(id='b1',shape='circle'){const fixed=['anchor','platform','arrow','text'].includes(shape),boxed=['rect','platform','triangle','arrow'].includes(shape);return {id,name:objectKinds.find(k=>k[0]===shape)?.[1]??'Тело',shape,color:'#4f56e8',x:0,y:3,vx:0,vy:0,mass:1,size:shape==='anchor'?.2:.35,...(boxed?{width:shape==='platform'?4:.7,height:shape==='platform'?.2:.5}:{}),angle:0,charge:shape==='charge'?1e-6:0,fieldEnabled:true,gravityEnabled:false,motion:'fixed',fx:'0',fy:'0',xFormula:'x0',yFormula:'y0',trail:!fixed,vector:shape==='charge'};}
