import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {validateModel} from './model.js';
import {validatePhysics} from './engine.js';
import {exampleFolders,examples} from './public-gallery.mjs';
const root=process.env.MODEL_STUDIO_DATA_DIR??path.join(path.dirname(fileURLToPath(import.meta.url)),'../data');
const modelsPath=path.join(root,'models');
const indexPath=path.join(root,'catalog.json');
const versionsPath=path.join(root,'versions');
async function rememberVersion(record){const dir=path.join(versionsPath,safeId(record.id));await fs.mkdir(dir,{recursive:true});await atomic(path.join(dir,record.revision+'.json'),record);const names=(await fs.readdir(dir)).filter(n=>/^\d+\.json$/.test(n)).sort((a,b)=>Number(b.split('.')[0])-Number(a.split('.')[0]));for(const name of names.slice(30))await fs.unlink(path.join(dir,name));}
export async function listVersions(id){const current=await getModel(id);let names=[];try{names=await fs.readdir(path.join(versionsPath,safeId(id)));}catch(e){if(e.code!=='ENOENT')throw e;}const records=await Promise.all(names.filter(n=>/^\d+\.json$/.test(n)).map(n=>fs.readFile(path.join(versionsPath,safeId(id),n),'utf8').then(JSON.parse)));return [current,...records.filter(r=>r.revision!==current.revision)].sort((a,b)=>b.revision-a.revision).map(r=>({revision:r.revision,updatedAt:r.updatedAt,title:r.spec.title,current:r.revision===current.revision}));}
export async function getVersion(id,revision){const current=await getModel(id);if(current.revision===revision)return current;if(!Number.isInteger(revision)||revision<1)throw new AppError('Некорректная версия');try{return JSON.parse(await fs.readFile(path.join(versionsPath,safeId(id),revision+'.json'),'utf8'));}catch(e){if(e.code==='ENOENT')throw new AppError('Версия не найдена',404);throw e;}}
export class AppError extends Error{constructor(message,status=400){super(message);this.status=status;}}
const safeId=id=>{if(typeof id!=='string'||!/^\w{1,80}$/.test(id))throw new AppError('Некорректное имя файла');return id;};
async function atomic(file,data){const temp=file+'.'+crypto.randomUUID()+'.tmp';await fs.writeFile(temp,JSON.stringify(data,null,2),'utf8');await fs.rename(temp,file);}
let queue=Promise.resolve();function serial(fn){const p=queue.then(fn);queue=p.catch(()=>{});return p;}
export async function initialize(){await fs.mkdir(modelsPath,{recursive:true});try{await fs.access(indexPath);}catch{const now=new Date().toISOString();for(const m of examples)await atomic(path.join(modelsPath,m.id+'.json'),{...m,revision:1,updatedAt:now,archived:0});await atomic(indexPath,{version:1,folders:exampleFolders});}}
async function catalog(){return JSON.parse(await fs.readFile(indexPath,'utf8'));}
export async function getModel(id){try{return JSON.parse(await fs.readFile(path.join(modelsPath,safeId(id)+'.json'),'utf8'));}catch(e){if(e.code==='ENOENT')throw new AppError('Модель не найдена',404);throw e;}}
export async function listLibrary(){const c=await catalog();const names=(await fs.readdir(modelsPath)).filter(f=>f.endsWith('.json'));const models=await Promise.all(names.map(async f=>JSON.parse(await fs.readFile(path.join(modelsPath,f),'utf8'))));models.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));return {folders:c.folders,models};}
async function checkFolder(id){if(id&&!((await catalog()).folders.some(f=>f.id===id)))throw new AppError('Папка не найдена',404);}
export function saveModel(a){return serial(async()=>{const spec=validatePhysics(validateModel(a.spec));const folderId=a.folderId??null;await checkFolder(folderId);let id=a.id,revision=1,archived=0;if(id){const old=await getModel(id);if(a.expectedRevision!==old.revision)throw new AppError('Модель изменена в другом окне или помощником. Экспортируйте свои изменения, обновите каталог и откройте последнюю версию.',409);await rememberVersion(old);revision=old.revision+1;archived=old.archived;}else id='model_'+crypto.randomUUID().replaceAll('-','');const result={id,folderId,spec,revision,archived,updatedAt:new Date().toISOString()};await atomic(path.join(modelsPath,safeId(id)+'.json'),result);return result;});}
export function createFolder(name,parentId=null){return serial(async()=>{if(typeof name!=='string'||!name.trim()||name.length>80)throw new AppError('Проверьте название папки');await checkFolder(parentId);const c=await catalog(),f={id:'folder_'+crypto.randomUUID().replaceAll('-',''),name:name.trim(),parentId};c.folders.push(f);await atomic(indexPath,c);return f;});}
export function renameFolder(id,name){return serial(async()=>{if(typeof name!=='string'||!name.trim()||name.length>80)throw new AppError('Проверьте название папки');const c=await catalog(),f=c.folders.find(f=>f.id===id);if(!f)throw new AppError('Папка не найдена',404);f.name=name.trim();await atomic(indexPath,c);return f;});}
export function deleteFolder(id){return serial(async()=>{const lib=await listLibrary();if(lib.models.some(m=>m.folderId===id)||lib.folders.some(f=>f.parentId===id))throw new AppError('Сначала переместите модели и удалите вложенные папки');await atomic(indexPath,{version:1,folders:lib.folders.filter(f=>f.id!==id)});});}
export function archiveModel(id,revision,archived){return serial(async()=>{const m=await getModel(id);if(revision!==m.revision)throw new AppError('Модель изменена. Обновите каталог.',409);await rememberVersion(m);m.archived=archived?1:0;m.revision++;m.updatedAt=new Date().toISOString();await atomic(path.join(modelsPath,safeId(id)+'.json'),m);return m;});}
export async function operation(a){switch(a.action){case 'versions':return listVersions(a.id);case 'version':return getVersion(a.id,a.revision);case 'save':return saveModel(a);case 'createFolder':return createFolder(a.name,a.parentId);case 'renameFolder':return renameFolder(a.id,a.name);case 'deleteFolder':return deleteFolder(a.id);case 'archive':return archiveModel(a.id,a.expectedRevision,a.archived);case 'move':{const m=await getModel(a.id);return saveModel({id:a.id,spec:m.spec,folderId:a.folderId,expectedRevision:a.expectedRevision});}default:throw new AppError('Неизвестное действие');}}
