import {evaluate,dependencies} from './expression.js';
import {validateControls} from './authoring.js';

export const bindingProperties={mass:['Масса','кг',1e-6,1e30],charge:['Заряд','Кл',-1e7,1e7],x:['Начальная x','м',-1e7,1e7],y:['Начальная y','м',-1e7,1e7],vx:['Начальная vₓ','м/с',-1e7,1e7],vy:['Начальная vᵧ','м/с',-1e7,1e7],size:['Радиус рисунка','м',.02,1000],angle:['Угол рисунка','°',-36000,36000]};
export function applyBindings(m){for(const p of m.parameters??[])if(p.binding){const b=m.bodies.find(b=>b.id===p.binding.body);if(b)b[p.binding.property]=p.value;}return m;}
export function validateTeaching(m){
 const fail=message=>{throw new Error(message);},text=(v,n=4000)=>typeof v==='string'&&v.length<=n,finite=v=>typeof v==='number'&&Number.isFinite(v);
 const list=(name,max)=>{if(m[name]!==undefined&&(!Array.isArray(m[name])||m[name].length>max))fail('Проверьте '+name);return m[name]??[];};
 const ids=new Set(),id=v=>{if(typeof v!=='string'||!/^[-A-Za-z0-9_]{1,80}$/.test(v)||ids.has(v))fail('Некорректное или повторное имя учебного элемента');ids.add(v);};
 for(const item of list('scenarios',20)){id(item.id);if(!text(item.title,100)||!item.title.trim()||!text(item.note))fail('Проверьте сценарий');if(m.kind==='html')validateControls(item.controls??[]);else{if(!item.parameters||typeof item.parameters!=='object'||Array.isArray(item.parameters))fail('Проверьте параметры сценария');for(const [key,value]of Object.entries(item.parameters)){const p=m.parameters.find(p=>p.id===key);if(!p||!finite(value)||value<p.min||value>p.max)fail('Параметр сценария вне диапазона: '+key);}if(item.camera){for(const key of ['x','y','zoom'])if(!finite(item.camera[key]))fail('Проверьте вид сценария');if(item.camera.zoom<.1||item.camera.zoom>30)fail('Проверьте масштаб сценария');}}}
 if(m.assignment!==undefined){const a=m.assignment;if(!a||!['prediction','experiment','explanation'].every(k=>text(a[k])))fail('Проверьте задание ученику');if(typeof a.hideResults!=='boolean')fail('Проверьте скрытие результатов');}
 if(m.kind==='html'){if(list('measurements',20).length||list('geometry',40).length||list('invariants',10).length)fail('Измерения и геометрия доступны в конструкторе');return m;}
 const bodies=new Map(m.bodies.map(b=>[b.id,b]));
 for(const p of m.parameters)if(p.binding){const b=bodies.get(p.binding.body),range=bindingProperties[p.binding.property];if(!b||!range||p.min<range[2]||p.max>range[3])fail('Проверьте связь ползунка со свойством');if(['x','y'].includes(p.binding.property)&&list('geometry',40).some(g=>g.target===p.binding.body))fail('Координаты зависимой точки задаются геометрией; используйте параметр ограничения');if(m.parameters.some(q=>q!==p&&q.binding?.body===p.binding.body&&q.binding?.property===p.binding.property))fail('У свойства уже есть ползунок');}
 for(const item of list('measurements',20)){id(item.id);if(!text(item.label,80)||!['distance','angle','vectors','probe'].includes(item.type))fail('Проверьте измерение');const keys=item.type==='distance'?['a','b']:item.type==='angle'?['a','vertex','b']:item.type==='vectors'?['a','b','c','d']:[];if(keys.some(k=>!bodies.has(item[k])))fail('Точка измерения не найдена');if(item.type==='probe'&&(!finite(item.x)||!finite(item.y)||Math.abs(item.x)>1e7||Math.abs(item.y)>1e7))fail('Проверьте координаты пробника');}
 const geometry=list('geometry',40),targets=new Map();
 for(const g of geometry){id(g.id);if(!['circle','equal','parallel','perpendicular'].includes(g.type)||!bodies.has(g.target)||targets.has(g.target))fail('Проверьте геометрическое ограничение');targets.set(g.target,g);const keys=g.type==='circle'?['target','center']:['target','center','a','b'];if(keys.some(k=>!bodies.has(g[k])||bodies.get(g[k]).motion!=='fixed'))fail('Геометрические ограничения требуют неподвижных точек');if(keys.slice(1).some(k=>g[k]===g.target))fail('Точка не может зависеть от самой себя');for(const key of ['length','angle']){if(!text(g[key],500)||!g[key].trim())fail('Проверьте формулу ограничения');for(const dep of dependencies(g[key]))if(!['pi','e',...m.parameters.map(p=>p.id)].includes(dep))fail('Геометрия: используйте только параметры и константы');}}
 const visited=new Set(),active=new Set();function visit(g){if(visited.has(g.target))return;if(active.has(g.target))fail('Цикл геометрических ограничений');active.add(g.target);for(const key of ['center','a','b'])if(targets.has(g[key]))visit(targets.get(g[key]));active.delete(g.target);visited.add(g.target);}for(const g of geometry)visit(g);
 for(const item of list('invariants',10)){id(item.id);if(!text(item.label,80)||!text(item.expression,500)||!finite(item.absolute)||!finite(item.relative)||item.absolute<0||item.relative<0)fail('Проверьте проверяемую величину');}
 for(const b of m.bodies)if(b.labelOffset!==undefined&&(!b.labelOffset||!finite(b.labelOffset.x)||!finite(b.labelOffset.y)||Math.abs(b.labelOffset.x)>500||Math.abs(b.labelOffset.y)>500))fail('Проверьте смещение подписи');
 return m;
}
// Geometry is a dependency graph of static construction points, never a force rule.
export function applyGeometry(m,s){
 const gs=m.geometry??[];if(!gs.length)return;const c=Object.fromEntries(m.parameters.map(p=>[p.id,p.value])),byTarget=new Map(gs.map(g=>[g.target,g])),done=new Set(),active=new Set();
 function place(g){if(done.has(g.target))return;if(active.has(g.target))throw new Error('Цикл геометрических ограничений');active.add(g.target);for(const key of ['center','a','b'])if(byTarget.has(g[key]))place(byTarget.get(g[key]));const center=s.bodies[g.center];let length=evaluate(g.length,c),angle=evaluate(g.angle,c)*Math.PI/180;
  if(g.type!=='circle'){const a=s.bodies[g.a],b=s.bodies[g.b],dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy);if(l<1e-12)throw new Error('Опорный отрезок геометрии имеет нулевую длину');if(g.type==='equal')length=l;else angle=Math.atan2(dy,dx)+(g.type==='perpendicular'?Math.PI/2:0);}
  if(!(length>0&&Number.isFinite(length)))throw new Error('Длина геометрического ограничения должна быть положительной');s.bodies[g.target]={x:center.x+length*Math.cos(angle),y:center.y+length*Math.sin(angle),vx:0,vy:0};active.delete(g.target);done.add(g.target);
 }for(const g of gs)place(g);
}
export function applyScenario(m,scenario){const next=structuredClone(m);if(next.kind==='html')next.initialControls=structuredClone(scenario.controls??[]);else{for(const p of next.parameters)if(Object.hasOwn(scenario.parameters,p.id))p.value=scenario.parameters[p.id];if(scenario.camera)next.scene.camera=structuredClone(scenario.camera);applyBindings(next);}return next;}
