import fs from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const targets={'DESKTOP.md':'/desktop.html','MODELS.md':'/models.html','VERSION-2.4.md':'/changes.html','EDITOR-NEXT.md':'/editor-next.html'};
const target=url=>targets[url]??(url.startsWith('../gallery/gallery_')?'/?model='+url.split('/').at(-1).replace('.json',''):url);
const inline=s=>esc(s).replace(/\[([^\]]+)\]\(([^)]+)\)/g,(_,label,url)=>`<a href="${target(url)}">${label}</a>`).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');
function markdown(s){return s.split(/\r?\n\s*\r?\n/).map(block=>{const lines=block.trim().split(/\r?\n/);if(!block.trim())return '';if(block.startsWith('```'))return '<pre><code>'+esc(lines.slice(1,-1).join('\n'))+'</code></pre>';if(lines.length>1&&/^\|[ :|-]+\|$/.test(lines[1])){const cells=line=>line.trim().slice(1,-1).split('|').map(cell=>inline(cell.trim()));return '<div class="guide-table"><table><thead><tr>'+cells(lines[0]).map(cell=>'<th>'+cell+'</th>').join('')+'</tr></thead><tbody>'+lines.slice(2).map(line=>'<tr>'+cells(line).map(cell=>'<td>'+cell+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}if(/^#{1,3} /.test(block)){const level=lines[0].match(/^#+/)[0].length;return `<h${level}>${inline(lines[0].slice(level+1))}</h${level}>`;}if(lines.every(l=>/^- /.test(l)))return '<ul>'+lines.map(l=>'<li>'+inline(l.slice(2))+'</li>').join('')+'</ul>';if(lines.every(l=>/^\d+\. /.test(l)))return '<ol>'+lines.map(l=>'<li>'+inline(l.replace(/^\d+\. /,''))+'</li>').join('')+'</ol>';return '<p>'+inline(lines.join(' '))+'</p>';}).join('\n');}
for(const [doc,out,title] of [['GUIDE.md','guide.html','Как пользоваться'],['MODELS.md','models.html','20 готовых моделей'],['DESKTOP.md','desktop.html','Отдельное приложение и сохранение'],['VERSION-2.4.md','changes.html','Изменения 2.4'],['EDITOR-NEXT.md','editor-next.html','Расширение редактора']]){const source=await fs.readFile(new URL('docs/'+doc,root),'utf8');const html=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — Модельная</title><script src="/theme-init.js"></script><link rel="stylesheet" href="/theme.css"><link rel="stylesheet" href="/guide.css"></head><body><nav><a href="/">← Открыть Модельную</a><a href="/guide.html">Руководство</a><a href="/models.html">Все модели</a><a href="/desktop.html">Приложение и сохранение</a></nav><main>${markdown(source)}</main></body></html>`;await fs.writeFile(new URL('web/'+out,root),html);}
console.log('Built-in documentation generated');
