import {esc} from './scene.js';
import {topicGroups,standardTopics,modelTopic,folderPath,catalogModels} from '/lib/topics.js';
export {modelTopic,folderPath,catalogModels};
export function allTopics(library){return [...new Set(library.models.filter(m=>!m.archived).map(m=>modelTopic(m.spec)))];}
export function topicField(spec,library=[]){const topics=[...new Set([...standardTopics,...library])];return `<label class="field"><span>Тема</span><input data-field="topic" list="topic-options" value="${esc(spec.topic??(modelTopic(spec)==='Без темы'?'':modelTopic(spec)))}" maxlength="80" placeholder="Выберите или напишите свою"><datalist id="topic-options">${topics.map(topic=>`<option value="${esc(topic)}"></option>`).join('')}</datalist></label>`;}
export function sidebarFolders(S,icon){const count=id=>catalogModels(S.library,{folder:id}).length;
 function branch(parent,depth){return S.library.folders.filter(f=>f.parentId===parent).map(folder=>{const children=S.library.folders.some(f=>f.parentId===folder.id),open=S.expanded.has(folder.id);return `<div class="folder-branch"><div class="folder-row ${S.folder===folder.id?'selected':''}" style="--folder-depth:${depth}">${children?`<button class="folder-toggle" data-toggle-folder="${folder.id}" aria-label="${open?'Свернуть':'Развернуть'} ${esc(folder.name)}" aria-expanded="${open}">${icon(open?'chevronDown':'chevronRight',14)}</button>`:'<span class="folder-toggle-spacer"></span>'}<button class="nav-item ${S.folder===folder.id?'active':''}" data-folder="${folder.id}" title="${esc(folder.name)}">${icon('folder')}<span class="folder-name">${esc(folder.name)}</span><small>${count(folder.id)}</small></button></div>${children&&open?`<div class="folder-children">${branch(folder.id,depth+1)}</div>`:''}</div>`;}).join('');}return branch(null,0);
}
export function sidebarTopics(S,icon){const count=topic=>catalogModels(S.library,{topic}).length;const custom=allTopics(S.library).filter(topic=>!standardTopics.includes(topic));return [...topicGroups,{subject:'other',label:'Другие темы',topics:custom}].filter(group=>group.topics.length).map(group=>{const open=S.expanded.has('topics:'+group.subject);return `<div class="topic-branch"><button class="topic-group-toggle" data-toggle-folder="topics:${group.subject}" aria-expanded="${open}">${icon(open?'chevronDown':'chevronRight',14)}${group.label}<small>${group.topics.reduce((sum,topic)=>sum+count(topic),0)}</small></button>${open?group.topics.map(topic=>`<button class="nav-item topic-nav ${S.topic===topic?'active':''}" data-topic-nav="${esc(topic)}" title="${esc(topic)}">${icon('folder')}<span class="folder-name">${esc(topic)}</span><small>${count(topic)}</small></button>`).join(''):''}</div>`;}).join('');}
export function breadcrumbs(S){if(S.folder==='all'&&S.topic==='all')return '';const path=folderPath(S.library.folders,S.folder);return `<nav class="breadcrumbs" aria-label="Расположение"><button data-folder="all">Все модели</button>${path.map(f=>`<span>/</span><button data-folder="${f.id}" ${f.id===S.folder?'aria-current="page"':''}>${esc(f.name)}</button>`).join('')}${S.folder==='trash'?'<span>/</span><span>Корзина</span>':''}${S.topic!=='all'?`<span>/</span><span>${esc(S.topic)}</span>`:''}</nav>`;}
export function folderTiles(S,icon){const children=S.library.folders.filter(f=>f.parentId===S.folder);return children.length?`<div class="folder-tiles">${children.map(f=>`<button data-folder="${f.id}" class="folder-tile">${icon('folder',22)}<span>${esc(f.name)}<small>${catalogModels(S.library,{folder:f.id}).length} ${pluralModels(catalogModels(S.library,{folder:f.id}).length)}</small></span>${icon('chevronRight',15)}</button>`).join('')}</div>`:'';}
export function catalogFilters(S,plural){const options=allTopics(S.library);return `<div class="catalog-controls"><label class="filter-field"><span>Тема</span><select id="topic-filter" aria-label="Тема моделей"><option value="all" ${S.topic==='all'?'selected':''}>Все темы</option>${options.map(topic=>`<option value="${esc(topic)}" ${S.topic===topic?'selected':''}>${esc(topic)}</option>`).join('')}</select></label><label class="filter-field"><span>Порядок</span><select id="sort-models" aria-label="Сортировка моделей">${[['recent','Недавно изменённые'],['title','По названию'],['topic','По теме']].map(([value,label])=>`<option value="${value}" ${S.sort===value?'selected':''}>${label}</option>`).join('')}</select></label><div id="filter-summary" class="filter-summary">${catalogModels(S.library,S).length} ${plural(catalogModels(S.library,S).length)}</div><button class="text-btn" data-a="reset-filters">Сбросить фильтры</button></div>`;}
export function groupedCards(models,S,cards){if(S.sort!=='topic'||!models.length)return cards(models);const groups=new Map();for(const model of models){const topic=modelTopic(model.spec);if(!groups.has(topic))groups.set(topic,[]);groups.get(topic).push(model);}return [...groups].map(([topic,items])=>`<section class="catalog-topic-group"><h2>${esc(topic)} <small>${items.length}</small></h2><div class="model-grid">${cards(items)}</div></section>`).join('');}

function pluralModels(n){return n%10===1&&n%100!==11?'модель':n%10>=2&&n%10<=4&&(n%100<12||n%100>14)?'модели':'моделей';}
