import {esc} from './scene.js';
import {connectionKinds,fieldKinds} from '/lib/components.js';
export function componentsInspector(m,tab,selection,{field,select,check,button,icon,section}){
 const list=m[tab]??[],item=list.find(c=>c.id===selection),add=tab==='connections'?'add-connection':'add-field';
 if(!item)return `<p class="hint intro">${tab==='connections'?'Соедините два объекта. Нить может провисать; пружина растягиваться и сжиматься; стержень сохраняет расстояние. Для неподвижного конца добавьте опору.':'Добавьте внешнее поле. Оно действует на объекты с движением «По действию сил»; несколько полей складываются.'}</p>${button(add,tab==='connections'?'Добавить связь':'Добавить поле','primary full','plus')}`;
 const index=list.indexOf(item),prefix=tab+'.'+index,common=`${field('Название',prefix+'.name',item.name)}${select('Тип',prefix+'.type',item.type,tab==='connections'?connectionKinds:fieldKinds)}${check('Учитывать в расчёте',prefix+'.enabled',item.enabled)}`;
 const bodies=m.bodies.map(b=>[b.id,b.name+' · '+b.id]);
 let detail='',targets='';
 if(tab==='connections'){detail=`${select('Первый конец',prefix+'.a',item.a,bodies)}${select('Второй конец',prefix+'.b',item.b,bodies)}${item.type==='line'?'<p class="hint">Линия служит для рисунка и не создаёт сил.</p>':`${field(item.type==='spring'?'Длина без деформации, м':'Длина, м',prefix+'.length',item.length,'number','min="0.02"')}<button class="text-btn" data-a="measure-link">Взять расстояние между концами</button>`}`;
  if(item.type==='spring')detail+=`${field('Жёсткость k, Н/м',prefix+'.stiffness',item.stiffness)}${field('Сопротивление c, Н·с/м',prefix+'.damping',item.damping)}<p class="hint">Можно указать число или имя параметра: <code>20</code>, <code>k</code>. Сила действует на оба конца: F = k(ℓ − L₀) + c·v вдоль связи.</p><p class="hint">Имя параметра связывает свойство с ползунком. Если заменить его числом, ползунок и авторские формулы измерений останутся прежними.</p>`;
  else if(item.type==='rope'||item.type==='rod')detail+=`<p class="hint">${item.type==='rope'?'Невесомая нерастяжимая нить тянет при натяжении и не толкает. При провисании натяжения нет.':'Невесомый стержень сохраняет расстояние между центрами; может тянуть и толкать.'} Концы прикреплены к центрам объектов. Вращение фигур не рассчитывается.</p>`;
 }else{
  const definitions={gravity:[['gₓ, м/с²','gx'],['gᵧ, м/с²','gy']],electric:[['Eₓ, Н/Кл','ex'],['Eᵧ, Н/Кл','ey']],magnetic:[['Bz, Тл','bz']],'magnetic-gradient':[['B₀, Тл','b0'],['Градиент по x, Тл/м','bxGradient'],['Градиент по y, Тл/м','byGradient'],['Начало x₀, м','originX'],['Начало y₀, м','originY']],drag:[['Коэффициент c, Н·с/м','drag']]};
  detail=(definitions[item.type]??[]).map(([label,key])=>field(label,prefix+'.'+key,item[key])).join('');
  detail+=`<p class="hint">${{gravity:'F = m·g. Для земного поля вниз: gₓ = 0, gᵧ = −9.81.',electric:'F = q·E. Задайте заряд в свойствах объекта; знак заряда меняет направление силы.',magnetic:'Bz направлено поперёк экрана: плюс — к нам (•), минус — от нас (×). Fₓ = q·vᵧ·Bz; Fᵧ = −q·vₓ·Bz.','magnetic-gradient':'Bz = B₀ + Gₓ(x−x₀) + Gᵧ(y−y₀). Индукция направлена поперёк экрана. Линии показывают одинаковое Bz, а не магнитный потенциал. Сила Лоренца вычисляется в положении каждой частицы.',drag:'Линейное сопротивление среды: F = −c·v; c ≥ 0. Сила направлена против скорости.'}[item.type]} Можно использовать параметры. Каждое однородное поле показано одним вектором с компонентами; длина стрелки условная. Электрический потенциал включает заряд и внешнее поле. Однородные поля с выборочными целями не имеют одной общей карты потенциала.</p>`;targets=`<label class="check"><input type="checkbox" data-field-all="${index}" ${item.all?'checked':''}>Все объекты с движением по силам</label>${m.bodies.map(b=>`<label class="check target-check"><input type="checkbox" data-field-target="${index}" data-body-target="${b.id}" ${item.all||item.targets.includes(b.id)?'checked':''}><span>${esc(b.name)}<small>${b.motion==='force'?'По действию сил':'Сейчас поле не меняет движение'}</small></span></label>`).join('')}`;
 }
 return `<div class="selected-object-name">${esc(item.name)}</div>`+section('main','Основные настройки',common)+section('physics',tab==='connections'?'Концы и физические свойства':'Характеристики поля',detail)+(targets?section('targets','Область действия',targets):'')+section('appearance','Отображение',field('Цвет',prefix+'.color',item.color,'color')+check('Показывать на сцене',prefix+'.show',item.show),{open:false})+`<div class="inspector-footer">${button(tab==='connections'?'duplicate-connection':'duplicate-field','Копия','quiet','copy')}${button(tab==='connections'?'delete-connection':'delete-field','Удалить','danger','trash')}</div>`+button(add,tab==='connections'?'Добавить ещё связь':'Добавить ещё поле','quiet full','plus');
}
export function componentList(m,tab,selection,icon){return `<div class="component-list">${(m[tab]??[]).map(item=>`<button data-select-component="${tab}:${item.id}" class="object-item ${selection===item.id?'selected':''}"><span class="component-symbol">${tab==='connections'?item.type==='spring'?'∿':item.type==='rope'?'⌁':'—':item.type==='magnetic'?'⊙':'↘'}</span><span>${esc(item.name)}<small>${(tab==='connections'?connectionKinds:fieldKinds).find(k=>k[0]===item.type)?.[1]??''}${item.enabled?'':' · выключено'}</small></span></button>`).join('')}</div>`;}
