import {electricSources,potentialLevels,potentialContours} from '/lib/electrostatics.js';
import {scalarField,fieldLayerEnabled} from '/lib/field-potential.js';
import {fieldValues} from '/lib/interaction.js';
// Bounded geometry cache: evaluated field values, source positions/radii and camera are part of the key.
const contourCache=new Map();
const fieldEscape=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fieldNumber=n=>Math.abs(n)>=1e5||Math.abs(n)>0&&Math.abs(n)<.001?n.toExponential(2).replace('.',','):n.toLocaleString('ru-RU',{maximumFractionDigits:3});
export function scalarFieldSVG(m,s,c,tr,type,small=false){if(!fieldLayerEnabled(m,type))return '';const f=scalarField(m,s,c,type);if(!f.active)return '';return contourSVG(f.sources,tr,f.levels,(sources,x,y)=>f.at(x,y),type,small,f.signature);}
export function chargeFieldSVG(m,s,tr,small=false,c={}){return scalarFieldSVG(m,s,c,tr,'electric',small);}
function contourSVG(sources,tr,levels,potential,type,small,signature){const labels=[],{r,X,Y,scale}=tr,key=JSON.stringify([type,sources,r,levels,small,signature]);let contours=contourCache.get(key);if(!contours){contours=potentialContours(sources,r,levels,small?48:100,small?32:64,potential);if(contourCache.size>=24)contourCache.delete(contourCache.keys().next().value);contourCache.set(key,contours);}let out='<g data-'+(type==='electric'?'charge-field':type+'-field')+'="true" fill="none" stroke-width="1.4" opacity=".75">';
 for(const contour of contours){if(!contour.segments.length)continue;const color=type==='gravity'?'var(--studio-green)':type==='magnetic'?'var(--studio-purple)':contour.level>0?'var(--studio-orange)':contour.level<0?'var(--studio-blue)':'var(--studio-muted)',path=contour.segments.map(([x,y,a,b])=>'M'+X(x).toFixed(2)+' '+Y(y).toFixed(2)+'L'+X(a).toFixed(2)+' '+Y(b).toFixed(2)).join('');
 out+='<path data-potential-level="'+contour.level+'" data-contour-kind="'+type+'" d="'+path+'" stroke="'+color+'" '+(contour.level===0?'stroke-dasharray="5 4"':'')+'/>';
 if(!small){const text=(type==='electric'?'φ = ':type==='gravity'?'Φg = ':'Bz = ')+fieldNumber(contour.level)+(type==='electric'?' В':type==='gravity'?' Дж/кг':' Тл'),width=text.length*6.2+10;const label=contour.segments.find(([x,y,a,b])=>{const px=(x+a)/2,py=(y+b)/2;return sources.every(q=>Math.hypot(px-q.x,py-q.y)*scale>35)&&X(px)>Math.max(65,tr.ox+5)&&X(px)+width<800-tr.ox-5&&Y(py)>tr.oy+115&&Y(py)<Math.min(405,450-tr.oy-11)&&labels.every(([lx,ly,lw])=>X(px)+width+6<lx||X(px)-6>lx+lw||Y(py)+10<ly-13||Y(py)-19>ly+6);});if(label){const [x,y,a,b]=label,px=X((x+a)/2),py=Y((y+b)/2);labels.push([px,py,width]);out+='<g data-potential-label="'+contour.level+'" stroke="none"><rect x="'+(px-4)+'" y="'+(py-13)+'" width="'+width+'" height="19" rx="4" fill="var(--studio-surface)" opacity=".94"/><text x="'+(px+1)+'" y="'+py+'" fill="'+color+'" font-size="12">'+text+'</text></g>';}}
 }return out+'</g>';
}
export function magneticFieldSVG(m,s,c,tr,small=false){if(!fieldLayerEnabled(m,'magnetic'))return '';const fields=(m.fields??[]).filter(f=>f.enabled&&f.type.startsWith('magnetic')&&(f.all??!f.targets.length));if(!fields.some(f=>f.show&&f.type==='magnetic-gradient'))return '';const total=fields.reduce((out,f)=>{const v=fieldValues(f,c);out.b+=v.bz;out.gx+=v.bxGradient??0;out.gy+=v.byGradient??0;return out;},{b:0,gx:0,gy:0}),{gx,gy}=total,at=(x,y)=>total.b+gx*x+gy*y;let out='';
 if(Math.hypot(gx,gy)<1e-12)return uniformFieldsSVG({...m,fields:[{...fields[0],id:'total_B',name:'Суммарное Bz',type:'magnetic',bz:String(at(0,0)),enabled:true,show:true}]},s,c,tr,small);
 const corners=[[tr.r.minX,tr.r.minY],[tr.r.minX,tr.r.maxY],[tr.r.maxX,tr.r.minY],[tr.r.maxX,tr.r.maxY]].map(([x,y])=>at(x,y)),lo=Math.min(...corners),hi=Math.max(...corners),raw=(hi-lo)/10,power=10**Math.floor(Math.log10(raw)),unit=[1,2,5,10].map(n=>n*power).find(n=>n>=raw),levels=[];for(let b=Math.ceil(lo/unit)*unit;b<=hi+unit*1e-8;b+=unit)levels.push(b);out+=contourSVG([],tr,levels,(_,x,y)=>at(x,y),'magnetic',small,[total.b,gx,gy]);
 for(let i=0;i<5;i++)for(let j=0;j<4;j++){const x=tr.r.minX+(i+.5)*(tr.r.maxX-tr.r.minX)/5,y=tr.r.minY+(j+.5)*(tr.r.maxY-tr.r.minY)/4,b=at(x,y);if(Math.abs(b)<1e-10)continue;const px=tr.X(x),py=tr.Y(y);out+='<g data-magnetic-direction="'+(b>0?'out':'in')+'" fill="none" stroke="var(--studio-purple)" opacity=".65"><circle cx="'+px+'" cy="'+py+'" r="6"/>'+(b>0?'<circle cx="'+px+'" cy="'+py+'" r="1.7" fill="var(--studio-purple)"/>':'<path d="M'+(px-3)+' '+(py-3)+'l6 6m-6 0l6-6"/>')+'</g>';}
 return out;}
export function uniformFieldsSVG(m,s,c,tr,small=false){let out='';const list=(m.fields??[]).filter(f=>f.enabled&&f.show&&f.type!=='magnetic-gradient'&&!(f.type==='magnetic'&&(f.all??!f.targets.length)&&(m.fields??[]).some(g=>g.enabled&&g.show&&g.type==='magnetic-gradient'&&(g.all??!g.targets.length))));for(let i=0;i<list.length;i++){const f=list[i];try{const v=fieldValues(f,c),columns=Math.max(1,Math.min(3,Math.floor((800-2*tr.ox)/185))),col=i%columns,row=Math.floor(i/columns),x=tr.ox+12+col*185,y=tr.oy+14+row*55,color=f.color;let vx=f.type==='gravity'?v.gx:f.type==='electric'?v.ex:0,vy=f.type==='gravity'?v.gy:f.type==='electric'?v.ey:0,detail=f.type==='gravity'?`g = (${fieldNumber(v.gx)}; ${fieldNumber(v.gy)}) м/с²`:f.type==='electric'?`E = (${fieldNumber(v.ex)}; ${fieldNumber(v.ey)}) Н/Кл`:f.type==='magnetic'?`Bz = ${fieldNumber(v.bz)} Тл`:`c = ${fieldNumber(v.drag)} Н·с/м`;
  if(f.type==='drag'){const body=m.bodies.find(b=>b.motion==='force'&&((f.all??!f.targets.length)||f.targets.includes(b.id))&&Math.hypot(s.bodies[b.id].vx,s.bodies[b.id].vy)>1e-10);if(body){vx=-s.bodies[body.id].vx;vy=-s.bodies[body.id].vy;}}
  out+=`<g data-field="${fieldEscape(f.id)}" data-uniform-field="true">${small?'':`<rect x="${x-5}" y="${y-7}" width="178" height="48" rx="7" fill="var(--studio-surface,#fff)" opacity=".92"/>`}`;
  if(f.type==='magnetic'){if(Math.abs(v.bz)>1e-12)out+=`<g data-field-vector="true" stroke="${color}" fill="none"><circle cx="${x+13}" cy="${y+16}" r="11" stroke-width="2"/>${v.bz>0?`<circle cx="${x+13}" cy="${y+16}" r="2.5" fill="${color}"/>`:`<path d="M${x+7} ${y+10}l12 12m-12 0l12-12" stroke-width="2"/>`}</g>`;}
  else{const length=Math.hypot(vx,vy);if(length>1e-12){const nx=vx/length,ny=-vy/length,ax=x+13-nx*15,ay=y+16-ny*15,bx=x+13+nx*15,by=y+16+ny*15;out+=`<path data-field-vector="true" d="M${ax} ${ay}L${bx} ${by}m${-nx*7-ny*4} ${-ny*7+nx*4}L${bx} ${by}l${-nx*7+ny*4} ${-ny*7-nx*4}" stroke="${color}" stroke-width="2.5" fill="none"/>`;}}
  if(!small)out+=`<text x="${x+37}" y="${y+8}" fill="var(--studio-ink,#26344b)" font-size="12">${fieldEscape(f.name.slice(0,19))}</text><text x="${x+37}" y="${y+26}" fill="${color}" font-size="11">${fieldEscape(detail)}</text>`;out+='</g>';
 }catch{}}return out;}
