import {panelToggle,panelHandle} from './panels.js';
import {esc} from './scene.js';
import {lessonDefinitions} from '/lib/lesson-models.js';
import {enrichmentDefinitions} from '/lib/enrichment-models.js';
const basicLessons=[...lessonDefinitions(),...enrichmentDefinitions()];
const colors={physics:'#4f56e8',math:'#239d86'};
export function htmlThumbnail(m){const basic=basicLessons.find(d=>m.sourceName==='public-gallery/v1/'+d.key||m.sourceName===(d.family==='enrichment'?'enrichment/v1/':'lesson-models/v1/')+d.key);if(basic){const v=Object.fromEntries(basic.parameters.map(p=>{const saved=Number(m.initialControls?.find(c=>c.id===p.id)?.value??p.value);return [p.id,Number.isFinite(saved)?Math.max(p.min,Math.min(p.max,saved)):p.value];}));return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 480" role="img" aria-label="${esc(m.title)}"><rect width="800" height="480" fill="var(--studio-plot)"/><g font-family="system-ui,sans-serif" font-size="16">${basic.draw(v,basic.calculate(v))}</g></svg>`;}const c=colors[m.subject],theme=m.previewTheme??'html';const line=(x1,y1,x2,y2,color='#96a5bd')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="4" stroke-linecap="round"/>`;let drawing='';
 if(['force','belt','slope','collision'].includes(theme)){
 if(theme==='slope')drawing=`<path d="M240 300 L560 300 L240 140 Z" fill="#e8ecf8" stroke="#9daac2" stroke-width="3"/><rect x="315" y="155" width="58" height="38" rx="7" fill="${c}" transform="rotate(26 344 174)"/>${line(390,223,465,260,c)}`;
 else if(theme==='collision')drawing=`${line(190,288,610,288)}<circle cx="340" cy="250" r="38" fill="${c}"/><circle cx="495" cy="260" r="28" fill="#e89137"/>${line(207,250,278,250,c)}<path d="M268 240l14 10-14 10" fill="none" stroke="${c}" stroke-width="4"/>`;
 else if(theme==='belt')drawing=`<rect x="220" y="130" width="360" height="190" rx="15" fill="#e8eef7" stroke="#b5c2d9" stroke-width="3"/>${[0,1,2,3].map(i=>line(240,165+i*35,560,165+i*35,'#c4cede')).join('')}<path d="M280 280 Q420 285 470 175" fill="none" stroke="${c}" stroke-width="4" stroke-dasharray="7 8"/><circle cx="430" cy="244" r="18" fill="${c}"/>`;
 else drawing=`${line(190,290,610,290)}<rect x="290" y="230" width="95" height="58" rx="8" fill="${c}"/>${line(378,236,500,170,'#e89137')}<path d="M476 171l26-2-12 23" fill="none" stroke="#e89137" stroke-width="4"/>`;
 }else if(theme==='trapezoid'||theme==='rectangle'){const points=theme==='trapezoid'?'240,290 560,290 465,160 335,160':'230,285 525,285 570,155 275,155';drawing=`<polygon points="${points}" fill="${c}15" stroke="${c}" stroke-width="4"/>${theme==='rectangle'?line(230,285,570,155,'#e89137')+line(525,285,275,155,'#9b7bb7'):''}`;
 }else if(theme==='cloth')drawing=`<rect x="270" y="185" width="80" height="110" rx="16" fill="${c}20" stroke="${c}" stroke-width="3"/><rect x="460" y="150" width="125" height="145" rx="3" fill="${c}20" stroke="${c}" stroke-width="3"/>${line(460,197,585,197)}${line(460,246,585,246)}`;
 else if(['glass','humidity','boiling'].includes(theme)){const cups=theme==='boiling'?[315,495]:[400];drawing=cups.map(x=>`<path d="M${x-48} 160 V295 H${x+48} V160" fill="none" stroke="#879ab7" stroke-width="4"/><rect x="${x-44}" y="220" width="88" height="70" fill="${c}25"/>${[0,1,2].map(i=>`<circle cx="${x-23+i*23}" cy="${180-i%2*20}" r="6" fill="${c}" opacity=".45"/>`).join('')}`).join('');}
 else drawing=`${line(210,270,590,270)}<circle cx="400" cy="270" r="25" fill="${c}"/>${line(210,155,210,290)}<path d="M250 235 Q355 135 440 195 T565 155" fill="none" stroke="${c}" stroke-width="4"/>`;
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 450" role="img" aria-label="${esc(m.title)}"><defs><pattern id="html-grid" width="32" height="32" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="#d1d9e8"/></pattern></defs><rect width="800" height="450" fill="#f8faff"/><rect width="800" height="450" fill="url(#html-grid)"/>${drawing}<text x="400" y="375" fill="#98a5bc" font-family="Segoe UI,Arial" font-size="19" text-anchor="middle">Интерактивная модель</text></svg>`;
}
export function htmlEditor(S,{icon,ib,button,field,select,folderOptions,themePicker=()=>'',topicField=()=>'',editorFeedback=()=>'',teachingBar=()=>''}){const m=S.draft;return `<div class="editor-shell html-editor ${S.present?'present':''}" data-panel-shell><header class="editor-header"><div class="editor-identity">${ib('back','back','Вернуться в каталог')}<span class="brand-mark small">М</span><div><strong>${esc(m.title)}</strong><small id="save-state">${S.experimentOnly?'Параметры текущего опыта · без сохранения':S.dirty?'Есть несохранённые изменения':'Сохранено в каталоге'}</small></div></div><div class="editor-actions">${themePicker()}${ib('undo','undo','Отменить')}${ib('redo','redo','Повторить')}${button('export','Экспорт','quiet','download')}${button('present',S.present?'Редактор':'Показ на уроке','quiet','eye')}${S.present?'':button('save',S.busy?'Сохраняем…':'Сохранить','primary','save')}</div></header>${editorFeedback(S)}<div id="teaching-kit">${teachingBar(S)}</div><div class="html-main"><main class="html-workspace">${S.present?'':`<div class="html-tabs"><button data-tab="details" class="${S.tab!=='source'?'active':''}">Модель</button><button data-tab="source" class="${S.tab==='source'?'active':''}">Исходный HTML</button>${button('capture-controls','Запомнить параметры','quiet','save')}</div>`}${S.tab==='source'&&!S.present?`<div class="html-source-panel"><p>Здесь можно изменить HTML, оформление и расчёты. Создайте копию перед изменением готового примера.</p><textarea id="html-source" spellcheck="false" wrap="off" aria-label="Исходный HTML модели">${esc(m.html)}</textarea><div>${button('html-preview','Применить и посмотреть','primary','eye')}</div></div>`:`<iframe id="html-frame" class="html-frame" sandbox="allow-scripts" title="${esc(m.title)}" referrerpolicy="no-referrer"></iframe>`}</main>${S.present?'':`<aside class="inspector"><div class="panel-heading"><h2>Модель и урок</h2></div><div class="inspector-content">${field('Название','title',m.title)}${field('Описание','description',m.description)}${topicField(m)}${field('Урок','lesson',m.lesson)}<div class="field-row">${select('Предмет','subject',m.subject,[['physics','Физика'],['math','Математика']])}</div><label class="field"><span>Папка в каталоге</span><select id="editor-folder">${folderOptions(S.folderId)}</select></label><label class="field"><span>Пояснение</span><textarea data-field="notes" rows="4">${esc(m.notes)}</textarea></label><div class="hint">Измените ползунки и сохраните модель — выбранные значения станут начальными при следующем открытии. Рисунок и расчёт редактируются во вкладке «Исходный HTML».</div>${m.sourceName?`<div class="html-source-name">Источник: ${esc(m.sourceName)}</div>`:''}</div>${panelHandle('properties','Ширина свойств модели')}</aside>`}</div></div>`;}
