import {esc} from './scene.js';
import {withHTMLTheme} from '/lib/theme.js';

export function htmlLessonExport(model,theme){
 const inner=withHTMLTheme(model.html,theme,model.initialControls);if(!(model.scenarios??[]).length&&!model.assignment)return inner;
 const data=JSON.stringify({scenarios:model.scenarios??[],assignment:model.assignment}).replaceAll('<','\\u003c').replaceAll('\u2028','\\u2028').replaceAll('\u2029','\\u2029');
 const script=`const lesson=${data},frame=document.querySelector('iframe');let phase='prediction';const answer={};function drawTask(){const a=lesson.assignment;if(!a)return;document.querySelector('#task-text').textContent=a[phase];document.querySelector('#answer').value=answer[phase]??'';frame.style.visibility=a.hideResults&&phase==='prediction'?'hidden':'visible';for(const b of document.querySelectorAll('[data-phase]'))b.setAttribute('aria-pressed',String(b.dataset.phase===phase));}document.querySelector('main').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.scenario!==undefined){const s=lesson.scenarios[Number(b.dataset.scenario)];frame.contentWindow.postMessage({type:'model-studio-apply-controls',controls:s.controls??[]},'*');document.querySelector('#scenario-note').textContent=s.note;}if(b.dataset.phase){phase=b.dataset.phase;drawTask();}});document.querySelector('#answer')?.addEventListener('input',e=>answer[phase]=e.target.value);drawTask();`;
 return withHTMLTheme(`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(model.title)}</title><style>body{margin:0;font-family:Segoe UI,Arial;background:#f6f7fb;color:#33415b}main{max-width:1200px;margin:auto;padding:20px}button{font:inherit;padding:10px;border:1px solid #dce3f0;background:white;color:#33415b;border-radius:8px;margin:4px;cursor:pointer}button[aria-pressed=true]{border-color:#4f56e8}iframe{width:100%;height:80vh;border:1px solid #dce3f0;border-radius:12px}textarea{display:block;width:100%;font:inherit;box-sizing:border-box}p{white-space:pre-wrap}</style></head><body><main><h1>${esc(model.title)}</h1><nav>${(model.scenarios??[]).map((s,i)=>`<button data-scenario="${i}">${esc(s.title)}</button>`).join('')}</nav><p id="scenario-note"></p>${model.assignment?`<section><h3>Предсказать → проверить → объяснить</h3>${[['prediction','1. Предсказание'],['experiment','2. Опыт'],['explanation','3. Объяснение']].map(([k,l])=>`<button data-phase="${k}">${l}</button>`).join('')}<p id="task-text"></p><label>Ответ ученика<textarea id="answer" rows="3"></textarea></label></section>`:''}<iframe sandbox="allow-scripts" srcdoc="${esc(inner)}" title="${esc(model.title)}"></iframe></main><script>${script}</script></body></html>`,theme);
}
