import {measure} from '/lib/measurements.js';
import {initialState,step,context} from '/lib/engine.js';
import {evaluate} from '/lib/expression.js';
import {sceneTransform} from '/lib/camera.js';
import {scalarField,fieldLayerEnabled} from '/lib/field-potential.js';
import {chargeFieldSVG,scalarFieldSVG,magneticFieldSVG,uniformFieldsSVG} from './field-drawing.js';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const fmt=v=>{if(!Number.isFinite(v))return '—';if(v===0)return '0';if(v!==0&&(Math.abs(v)<.001||Math.abs(v)>=1e7)){const [mantissa,exponent]=v.toExponential(3).split('e'),sup={'-':'⁻','0':'⁰','1':'¹','2':'²','3':'³','4':'⁴','5':'⁵','6':'⁶','7':'⁷','8':'⁸','9':'⁹'};return mantissa.replace('.',',')+' × 10'+String(Number(exponent)).split('').map(c=>sup[c]).join('');}return v.toLocaleString('ru-RU',{maximumFractionDigits:3});};
export function sceneSVG(m,s,history=[],selected=null,small=false){const W=800,H=450,tr=sceneTransform(m.scene,small),{r,scale,ox,oy,X,Y}=tr,dx=r.maxX-r.minX,dy=r.maxY-r.minY;
 let out=`<svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg" aria-label="Сцена модели" role="img" data-scene="true"><defs><pattern id="dots" width="${Math.max(10,scale)}" height="${Math.max(10,scale)}" patternUnits="userSpaceOnUse" x="${X(0)}" y="${Y(0)}"><circle cx="1" cy="1" r="1" fill="#cfd6e3"/></pattern><marker id="vector" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#ee8a36"/></marker><clipPath id="sceneClip"><rect x="${ox}" y="${oy}" width="${dx*scale}" height="${dy*scale}"/></clipPath></defs><rect width="800" height="450" fill="#f8faff"/>`;
 if(m.scene.grid){const raw=Math.max(dx,dy)/12,power=10**Math.floor(Math.log10(raw)),step=[1,2,5,10].map(k=>k*power).find(k=>k>=raw);for(let x=Math.ceil(r.minX/step)*step;x<=r.maxX+step*1e-6;x+=step)out+=`<line x1="${X(x)}" x2="${X(x)}" y1="${oy}" y2="${H-oy}" stroke="var(--studio-line,#dce3ee)" opacity=".55"/>`;for(let y=Math.ceil(r.minY/step)*step;y<=r.maxY+step*1e-6;y+=step)out+=`<line y1="${Y(y)}" y2="${Y(y)}" x1="${ox}" x2="${W-ox}" stroke="var(--studio-line,#dce3ee)" opacity=".55"/>`;}
 if(r.minY<=0&&r.maxY>=0)out+=`<line x1="${ox}" x2="${W-ox}" y1="${Y(0)}" y2="${Y(0)}" stroke="#c8d0df" stroke-width="1.4"/>`;
 if(r.minX<=0&&r.maxX>=0)out+=`<line y1="${oy}" y2="${H-oy}" x1="${X(0)}" x2="${X(0)}" stroke="#c8d0df" stroke-width="1.4"/>`;
 if(!small){for(let i=0;i<=5;i++){const x=r.minX+dx*i/5,y=r.minY+dy*i/5;out+=`<text x="${X(x)}" y="${H-12}" font-size="12" text-anchor="middle" fill="#8090a8">${fmt(x)}</text><text x="12" y="${Y(y)+4}" font-size="12" fill="#8090a8">${fmt(y)}</text>`;}out+=`<text x="770" y="${H-12}" font-size="13" fill="#61718c">x${m.subject==='physics'?', м':''}</text><text x="10" y="20" font-size="13" fill="#61718c">y${m.subject==='physics'?', м':''}</text>`;}
 out+='<g clip-path="url(#sceneClip)">';
 const visibleFields=(m.fields??[]).filter(f=>f.enabled&&f.show);let fieldContext;try{fieldContext=context(m,s);}catch{}
 out+=chargeFieldSVG(m,s,tr,small,fieldContext??{})+scalarFieldSVG(m,s,fieldContext??{},tr,'gravity',small)+magneticFieldSVG(m,s,fieldContext??{},tr,small)+uniformFieldsSVG(m,s,fieldContext??{},tr,small);
 for(const link of m.connections??[]){if(!link.show)continue;const a=s.bodies[link.a],b=s.bodies[link.b];if(!a||!b)continue;const ax=X(a.x),ay=Y(a.y),bx=X(b.x),by=Y(b.y),px=bx-ax,py=by-ay,L=Math.hypot(px,py),nx=L?px/L:1,ny=L?py/L:0;let path=`M${ax} ${ay}L${bx} ${by}`;
  if(link.type==='spring')path=`M${ax} ${ay}L${ax+px*.12} ${ay+py*.12}${Array.from({length:16},(_,i)=>{const u=.12+.76*(i+1)/17,w=(i%2?1:-1)*7;return `L${ax+px*u-ny*w} ${ay+py*u+nx*w}`;}).join('')}L${ax+px*.88} ${ay+py*.88}L${bx} ${by}`;
  if(link.type==='rope'&&L<link.length*scale-.01){let normalX=-ny,normalY=nx;if(normalY<0){normalX=-normalX;normalY=-normalY;}const sag=Math.sqrt(Math.max(0,(link.length*scale)**2-L*L))/2;path=`M${ax} ${ay}L${(ax+bx)/2+normalX*sag} ${(ay+by)/2+normalY*sag}L${bx} ${by}`;}
  out+=`<g data-connection="${esc(link.id)}" opacity="${link.enabled?1:.35}"><path d="${path}" fill="none" stroke="${selected===link.id?'var(--studio-accent,#4f56e8)':link.color}" stroke-width="${link.type==='rod'?5:2.5}" ${link.type==='line'?'stroke-dasharray="5 4"':''}/>${small?'':`<path d="${path}" fill="none" stroke="transparent" stroke-width="14" style="cursor:pointer"/>${link.type==='line'?'':`<text x="${(ax+bx)/2}" y="${(ay+by)/2-12}" text-anchor="middle" fill="var(--studio-muted,#65758d)" font-size="12">${esc(link.name)}</text>`}` }</g>`;
 }
 const labelBoxes=[];for(const b of m.bodies){const v=s.bodies[b.id];if(v&&b.gravityRadius>0){const rr=b.gravityRadius*scale;out+='<g data-gravity-sphere="'+esc(b.id)+'"><circle cx="'+X(v.x)+'" cy="'+Y(v.y)+'" r="'+rr+'" fill="var(--studio-green,#23a08c)" fill-opacity=".06" stroke="var(--studio-green,#23a08c)" stroke-width="2" stroke-dasharray="6 4"/>'+(small?'':'<text x="'+X(v.x)+'" y="'+(Y(v.y)-rr+18)+'" text-anchor="middle" font-size="12" fill="var(--studio-green,#23a08c)">Однородный шар · R = '+fmt(b.gravityRadius)+' м</text>')+'</g>';}}
 for(const b of m.bodies){const v=s.bodies[b.id];if(!v)continue;const xx=X(v.x),yy=Y(v.y),size=b.shape==='point'?5:b.size*scale,width=(b.width??b.size*2)*scale,height=(b.height??b.size*1.4)*scale;if(b.trail&&history.length>1){const pts=history.filter((_,i)=>i%2===0).map(h=>h.bodies[b.id]).filter(Boolean).map(h=>`${X(h.x)},${Y(h.y)}`).join(' ');out+=`<polyline points="${pts}" fill="none" stroke="${b.color}" stroke-width="2" opacity=".32" stroke-linecap="round"/>`;}
 out+=`<g data-body="${esc(b.id)}" class="scene-body" style="cursor:${small?'default':'grab'}">`;
 const boxed=['rect','platform','triangle','arrow'].includes(b.shape),halfW=boxed?width/2:size,halfH=boxed?height/2:size;
 out+=`<g transform="translate(${xx} ${yy}) rotate(${-(b.angle??0)})">`;
 if(selected===b.id&&!small)out+=`<rect x="${-halfW-7}" y="${-halfH-7}" width="${2*halfW+14}" height="${2*halfH+14}" rx="8" fill="${b.color}12" stroke="${b.color}" stroke-dasharray="4 4"/>`;
 if(b.shape==='rect'||b.shape==='platform')out+=`<rect x="${-width/2}" y="${-height/2}" width="${width}" height="${height}" rx="${b.shape==='platform'?0:Math.min(8,height/4)}" fill="${b.color}"/>${b.shape==='platform'?Array.from({length:9},(_,i)=>`<path d="M${-width/2+i*width/8} ${height/2}l-7 9" stroke="${b.color}" stroke-width="2"/>`).join(''):''}`;
 else if(b.shape==='triangle')out+=`<path d="M0 ${-height/2}L${width/2} ${height/2}L${-width/2} ${height/2}Z" fill="${b.color}"/>`;
 else if(b.shape==='arrow')out+=`<path d="M${-width/2} ${-height*.15}H${width*.15}V${-height/2}L${width/2} 0L${width*.15} ${height/2}V${height*.15}H${-width/2}Z" fill="${b.color}"/>`;
 else if(b.shape==='text')out+=`<text x="0" y="0" text-anchor="middle" fill="${b.color}" font-size="${Math.max(16,size)}">${esc(b.name)}</text>`;
 else if(b.shape==='ring')out+=`<circle r="${size}" fill="none" stroke="${b.color}" stroke-width="3"/><circle r="${size}" fill="transparent"/>`;
 else if(b.shape==='anchor')out+=`<circle r="${size}" fill="var(--studio-surface,#fff)" stroke="${b.color}" stroke-width="3"/><path d="M${-size*.6} 0H${size*.6}M0 ${-size*.6}V${size*.6}" stroke="${b.color}" stroke-width="2"/>`;
 else{out+=`<circle r="${size}" fill="${b.color}"/>`;if(b.shape==='charge')out+=`<text y="${size*.3}" text-anchor="middle" fill="white" font-size="${Math.max(12,size*1.4)}">${(b.charge??0)>0?'+':(b.charge??0)<0?'−':'0'}</text>`;else out+=`<circle cx="${-size*.28}" cy="${-size*.28}" r="${size*.18}" fill="white" opacity=".35"/>`;}
 out+='</g>';
 if(b.shape!=='text'&&!small){let offset=b.labelOffset??{x:0,y:0},lx=xx+offset.x,ly=yy-Math.max(halfH,size)-14+offset.y;const width=Math.min(250,b.name.length*8);if(!b.labelOffset)for(let n=0;n<9;n++){const box={x:lx-width/2,y:ly-14,w:width,h:18};if(!labelBoxes.some(r=>box.x<r.x+r.w&&box.x+box.w>r.x&&box.y<r.y+r.h&&box.y+box.h>r.y)){break;}ly-=20;offset={x:0,y:ly-(yy-Math.max(halfH,size)-14)};}labelBoxes.push({x:lx-width/2,y:ly-14,w:width,h:18});out+=`<text data-label="${esc(b.id)}" data-label-x="${offset.x}" data-label-y="${offset.y}" style="cursor:move" x="${lx}" y="${ly}" text-anchor="middle" fill="var(--studio-ink,#44516b)" font-size="14" font-weight="500">${esc(b.name)}</text>`;}
 out+='</g>';
 if(b.vector&&!small&&Math.hypot(v.vx,v.vy)>1e-7){const length=Math.min(100,Math.hypot(v.vx,v.vy)*10),angle=Math.atan2(v.vy,v.vx);out+=`<line x1="${xx}" y1="${yy}" x2="${xx+length*Math.cos(angle)}" y2="${yy-length*Math.sin(angle)}" stroke="#ee8a36" stroke-width="2" marker-end="url(#vector)"/>`;}
 }out+='</g>';
 if(!small&&visibleFields.some(f=>f.type!=='magnetic-gradient'))out+=`<text x="70" y="22" font-size="12" fill="var(--studio-muted,#65758d)">Однородные поля · один вектор на поле</text>`;
 if(!small&&fieldLayerEnabled(m,'electric')&&scalarField(m,s,fieldContext??{},'electric').active)out+='<text x="70" y="38" font-size="12" fill="var(--studio-muted,#65758d)">Суммарный электрический потенциал · φ, В</text>';
 if(!small&&fieldLayerEnabled(m,'gravity')&&scalarField(m,s,fieldContext??{},'gravity').active)out+='<text x="70" y="54" font-size="12" fill="var(--studio-green)">Гравитационный потенциал · Φg, Дж/кг</text>';
 if(!small&&fieldLayerEnabled(m,'magnetic')&&(m.fields??[]).some(f=>f.enabled&&f.show&&f.type==='magnetic-gradient'&&(f.all??!f.targets.length)))out+='<text x="70" y="70" font-size="12" fill="var(--studio-purple)">Bz · линии равной индукции, не потенциал</text>';
 if(!m.bodies.length)out+='<text x="400" y="225" text-anchor="middle" font-size="16" fill="#8390a8">Добавьте первый объект на сцену</text>';
 if(!small&&m.bodies.some(b=>b.vector))out+='<text x="790" y="22" text-anchor="end" font-size="12" fill="#b0723d">Стрелки скорости · длина условная</text>';
 if(!small)for(const q of m.measurements??[]){try{const v=measure(m,s,q,fieldContext??context(m,s)),point=id=>s.bodies[id],line=(a,b)=>`<line x1="${X(a.x)}" y1="${Y(a.y)}" x2="${X(b.x)}" y2="${Y(b.y)}" stroke="var(--studio-orange)" stroke-width="2" stroke-dasharray="5 4"/>`;let anchor;if(q.type==='probe'){anchor={x:q.x,y:q.y};out+=`<path d="M${X(q.x)-7} ${Y(q.y)}h14m-7-7v14" stroke="var(--studio-orange)" stroke-width="2"/>`;}else if(q.type==='distance'){const a=point(q.a),b=point(q.b);out+=line(a,b);anchor={x:(a.x+b.x)/2,y:(a.y+b.y)/2};}else if(q.type==='angle'){anchor=point(q.vertex);out+=line(anchor,point(q.a))+line(anchor,point(q.b));const A=point(q.a),B=point(q.b),start=Math.atan2(-(A.y-anchor.y),A.x-anchor.x),end=Math.atan2(-(B.y-anchor.y),B.x-anchor.x),delta=Math.atan2(Math.sin(end-start),Math.cos(end-start)),radius=Math.min(30,Math.hypot(A.x-anchor.x,A.y-anchor.y)*scale*.35,Math.hypot(B.x-anchor.x,B.y-anchor.y)*scale*.35);out+=`<path d="M${X(anchor.x)+radius*Math.cos(start)} ${Y(anchor.y)+radius*Math.sin(start)}A${radius} ${radius} 0 0 ${delta>=0?1:0} ${X(anchor.x)+radius*Math.cos(start+delta)} ${Y(anchor.y)+radius*Math.sin(start+delta)}" fill="none" stroke="var(--studio-orange)" stroke-width="2"/>`;}else{out+=line(point(q.a),point(q.b))+line(point(q.c),point(q.d));anchor=point(q.a);}out+=`<text x="${X(anchor.x)+8}" y="${Y(anchor.y)-8}" fill="var(--studio-orange)" font-size="13" paint-order="stroke" stroke="var(--studio-plot)" stroke-width="4">${esc(q.label)}${q.type==='probe'?'':': '+fmt(v.value)+' '+v.unit}</text>`;}catch{}}return out+'</svg>';}
const previewCache=new Map();
export function preview(m){const key=JSON.stringify(m);if(previewCache.has(key))return previewCache.get(key);const result=buildPreview(m);if(previewCache.size>=64)previewCache.delete(previewCache.keys().next().value);previewCache.set(key,result);return result;}
function buildPreview(m){try{let s=initialState(m);const history=[structuredClone(s)],d=Math.min(m.duration,m.dt*200)/50;for(let i=0;i<50;i++){let end=Math.min(m.duration,m.dt*200,s.t+d);while(s.t<end-1e-8)s=step(m,s,Math.min(m.dt,end-s.t));history.push(structuredClone(s));}return sceneSVG(m,history[Math.floor(history.length*.4)],history,null,true);}catch{return sceneSVG(m,{t:0,bodies:Object.fromEntries(m.bodies.map(b=>[b.id,{x:b.x,y:b.y,vx:b.vx,vy:b.vy}]))},[],null,true);}}
export function graphSVG(m,history,g,index=0){
 const W=500,H=170,p=32,values=history.map(s=>{try{return {t:s.t,v:evaluate(g.expression,context(m,s))};}catch{return null;}}).filter(v=>v&&Number.isFinite(v.v)),fixed=g.autoScale===false;
 let lo=fixed?g.minY:Math.min(...values.map(v=>v.v)),hi=fixed?g.maxY:Math.max(...values.map(v=>v.v));
 if(!values.length&&!fixed){lo=0;hi=1;}if(!fixed){const padding=hi>lo?(hi-lo)*.12:Math.max(Math.abs(lo)*.12,1e-9);lo-=padding;hi+=padding;}
 if(!Number.isFinite(lo)||!Number.isFinite(hi)||!(hi>lo))return '<p role="alert">Проверьте диапазон графика: максимум должен быть больше минимума.</p>';
 const X=t=>p+t/Math.max(m.duration,.1)*(W-p-12),Y=v=>H-p-(v-lo)/(hi-lo)*(H-p-16),color=['var(--studio-accent,#4f56e8)','var(--studio-green,#23a08c)','var(--studio-orange,#e89137)','var(--studio-purple,#d65b9a)'][index%4],clip='graphClip'+index;
 return '<svg viewBox="0 0 '+W+' '+H+'" role="img" aria-label="'+esc(g.label)+'" data-graph-min="'+lo+'" data-graph-max="'+hi+'" data-graph-scale="'+(fixed?'fixed':'auto')+'"><defs><clipPath id="'+clip+'"><rect x="'+p+'" y="16" width="'+(W-p-12)+'" height="'+(H-p-16)+'"/></clipPath></defs><path d="M'+p+' 16V'+(H-p)+'H'+(W-12)+'" fill="none" stroke="var(--studio-line,#d9dfeb)"/><g clip-path="url(#'+clip+')">'+(lo<=0&&hi>=0?'<line x1="'+p+'" y1="'+Y(0)+'" x2="'+(W-12)+'" y2="'+Y(0)+'" stroke="var(--studio-line,#e9edf5)" stroke-dasharray="4 4"/>':'')+'<polyline fill="none" stroke="'+color+'" stroke-width="2.3" stroke-linecap="round" points="'+values.map(v=>X(v.t)+','+Y(v.v)).join(' ')+'"/></g><g fill="var(--studio-muted,#8a97ab)" font-size="11"><text x="'+(p+4)+'" y="28">'+fmt(hi)+'</text><text x="'+(p+4)+'" y="'+(H-p-6)+'">'+fmt(lo)+'</text><text x="'+(W-16)+'" y="28" text-anchor="end">'+(fixed?'Масштаб фиксирован':'Автомасштаб')+'</text><text x="'+p+'" y="'+(H-8)+'">0</text><text x="'+(W-12)+'" y="'+(H-8)+'" text-anchor="end">t, с · '+fmt(m.duration)+'</text></g></svg>';
}
