import {esc} from './scene.js';
import {withHTMLTheme} from '/lib/theme.js';
import {lessonGuide} from '/lib/lesson-guide.js';

export function studentHTML(model,html,instructions,theme){
 if(typeof instructions!=='string'||instructions.length>4000)throw Error('Инструкция: максимум 4 000 символов');
 return withHTMLTheme(`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(model.title)} — учебный опыт</title><style>body{margin:0;font:16px/1.6 system-ui;background:#f6f8fc;color:#33415b}main{max-width:1200px;margin:auto;padding:20px}h1{font-size:26px}p{white-space:pre-wrap}details{padding:14px;border:1px solid #8390a8;border-radius:10px;margin-bottom:14px}iframe{width:100%;height:85vh;min-height:480px;border:1px solid #8390a8;border-radius:10px;background:transparent}button{font:inherit;padding:10px;border-radius:8px;border:1px solid #8390a8;background:transparent;color:inherit;cursor:pointer}@media(max-width:480px){main{padding:12px}h1{font-size:22px}}</style></head><body><main><h1>${esc(model.title)}</h1><p>Этот файл работает без интернета. Меняйте параметры в опыте и записывайте результаты отдельно.</p><details open><summary>Инструкция к опыту</summary><p>${esc(instructions)}</p></details><button type="button" id="student-fullscreen">На весь экран</button><p id="student-status" role="status"></p><iframe sandbox="allow-scripts" srcdoc="${esc(html)}" title="${esc(model.title)}"></iframe></main><script>document.getElementById('student-fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{document.getElementById('student-status').textContent='Полный экран недоступен. Разверните окно браузера.';}};document.addEventListener('fullscreenchange',()=>{document.getElementById('student-fullscreen').textContent=document.fullscreenElement?'Выйти из полноэкранного режима':'На весь экран';});</script></body></html>`,theme);
}
export function studentDialog(env){
 const model=structuredClone(env.model()),instructions=lessonGuide(model);
 env.dialog('Подготовить опыт для ученика',`<div class="student-guide"><ol><li><strong>Редактируемый проект.</strong> Чтобы сохранить собственный вариант в каталоге, создайте копию. JSON передают для дальнейшего редактирования.</li><li><strong>Настройте опыт.</strong> HTML возьмёт текущие параметры открытой модели. Подпишите, что должен проверить ученик.</li><li><strong>Передайте один HTML-файл.</strong> Ученик открывает его двойным щелчком в современном браузере. Приложение и интернет не нужны.</li></ol><button type="button" class="btn quiet" data-a="save-copy">Сохранить копию в каталоге</button><label class="field"><span>Инструкция для ученика</span><textarea name="instructions" aria-label="Инструкция для ученика" rows="8" maxlength="4000">${esc(instructions)}</textarea></label><p>Инструкция войдёт в HTML; сохранённый проект не меняется. Ответы ученик записывает отдельно.</p></div>`,'Скачать HTML для ученика',async form=>{
  const html=await env.build(model);env.download(env.fileName(model.title)+'-учебный-опыт.html',studentHTML(model,html,form.get('instructions'),env.theme()),'text/html;charset=utf-8');
  env.toast('HTML готов: передайте ученику один файл.');
 });
}
