import {esc,fmt,sceneSVG,graphSVG} from './scene.js';
import {bindingProperties,applyBindings,applyScenario} from '/lib/teaching.js';
import {auditModel} from '/lib/audit.js';
import {initialState,step,context} from '/lib/engine.js';
import {evaluate} from '/lib/expression.js';
import {validatePhysics} from '/lib/engine.js';
import {validateModel} from '/lib/model.js';
import {measure} from '/lib/measurements.js';

export function teachingBar(S){const native=S.draft.kind!=='html',m=S.draft,a=m.assignment,phase=S.lessonPhase??'prediction';return `<div class="teaching-bar" aria-label="Инструменты занятия">${S.present?'':'<button class="btn quiet" data-a="teach-lesson">Урок: сценарии и задание</button>'}${native?'<button class="btn quiet" data-a="teach-measure">Измерить</button>':''}${native&&!S.present?'<button class="btn quiet" data-a="teach-geometry">Геометрия</button><button class="btn quiet" data-a="teach-slider">Свойство → ползунок</button>':''}${native?`<button class="btn quiet" data-a="teach-compare">${S.comparison?'Настроить сравнение':'Сравнить опыты'}</button>${S.comparison?'<button class="btn quiet" data-a="teach-stop-compare">Один опыт</button>':''}`:''}${S.present?'':'<button class="btn quiet" data-a="teach-audit">Проверить модель</button><button class="btn quiet" data-a="teach-versions">История версий</button>'}</div>${(m.scenarios??[]).length?`<div class="scenario-strip" aria-label="Сценарии урока">${m.scenarios.map((s,i)=>`<button class="btn quiet" data-a="teach-scenario:${i}">${esc(s.title)}</button>`).join('')}<span class="scenario-note">${esc(S.scenarioNote??'')}</span></div>`:''}${a&&(a.prediction||a.experiment||a.explanation)?`<details class="lesson-task" ${S.present?'open':''}><summary>Задание: предсказать → проверить → объяснить</summary><nav aria-label="Этап задания">${[['prediction','1. Предсказание'],['experiment','2. Опыт'],['explanation','3. Объяснение']].map(([key,label])=>`<button data-a="teach-phase:${key}" aria-pressed="${key===phase}">${label}</button>`).join('')}</nav><p>${esc(a[phase]).replaceAll('\n','<br>')}</p><label class="field"><span>Мой ответ · в текущем сеансе</span><textarea rows="2" data-lesson-answer="${phase}" aria-label="Ответ ученика">${esc(S.lessonAnswers?.[phase]??'')}</textarea></label>${S.present&&a.hideResults&&phase==='prediction'?'<p class="hint">Результаты откроются на этапе «Опыт».</p>':''}</details>`:''}`;}
export function initTeaching(S,h){
 const {dialog,button,render,pushUndo,changed,api,toast,captureControls,applySavedControls,saveDraft,updateScene}=h;
 const options=selected=>S.draft.bodies.map(b=>`<option value="${b.id}" ${b.id===selected?'selected':''}>${esc(b.name)} · ${b.id}</option>`).join('');
 const pick=(name,label,value)=>`<label class="field"><span>${label}</span><select name="${name}">${options(value??S.draft.bodies[name==='target'?Math.min(2,S.draft.bodies.length-1):name==='b'?1:0]?.id)}</select></label>`;
 const input=(name,label,value='',type='text')=>`<label class="field"><span>${label}</span><input name="${name}" type="${type}" ${type==='number'?'step="any"':''} value="${esc(value)}" required></label>`;
 const uid=prefix=>prefix+'_'+crypto.randomUUID().replaceAll('-','');
 const mutate=fn=>{const next=structuredClone(S.draft);fn(next);validatePhysics(validateModel(next));pushUndo();S.draft=next;changed();render();};
 async function handle(name){if(!name.startsWith('teach-'))return false;const [action,arg]=name.split(':');
 switch(action){
 case 'teach-lesson':{const a=S.draft.assignment??{prediction:'',experiment:'',explanation:'',hideResults:true};dialog('Сценарии и задание',`<p class="hint">Сценарий хранит параметры и вид плоскости. В конструкторе опыт начинается с t = 0; в HTML ход анимации задаёт сценарий самого урока. Сначала настройте модель, затем запомните сценарий.</p><div class="menu-actions">${button('teach-new-scenario','Запомнить текущую настройку','quiet full')}${(S.draft.scenarios??[]).map((s,i)=>`<div class="scenario-edit"><span>${esc(s.title)}</span>${button('teach-scenario:'+i,'Открыть','quiet')}${button('teach-edit-scenario:'+i,'Название и пояснение','quiet')}${button('teach-delete-scenario:'+i,'Удалить','danger')}</div>`).join('')}</div>${['prediction','experiment','explanation'].map((key,i)=>`<label class="field"><span>${['Предсказание ученика','Условие опыта','Вопрос для объяснения'][i]}</span><textarea name="${key}" rows="3" maxlength="4000">${esc(a[key])}</textarea></label>`).join('')}<label class="check"><input name="hide" type="checkbox" ${a.hideResults?'checked':''}>Скрывать результаты до опыта в показе ученику</label><p class="hint">У HTML-урока до этапа «Опыт» скрывается вся демонстрация; его внутренние результаты задаёт автор HTML.</p>`,'Сохранить задание',async data=>mutate(m=>m.assignment={prediction:data.get('prediction'),experiment:data.get('experiment'),explanation:data.get('explanation'),hideResults:!!data.get('hide')}));break;}
 case 'teach-edit-scenario':{const scenario=S.draft.scenarios?.[Number(arg)];if(!scenario)break;dialog('Изменить сценарий',input('title','Название сценария',scenario.title)+`<label class="field"><span>Пояснение к шагу</span><textarea name="note" rows="3" maxlength="4000">${esc(scenario.note)}</textarea></label>`,'Сохранить',async data=>mutate(m=>{m.scenarios[Number(arg)].title=data.get('title');m.scenarios[Number(arg)].note=data.get('note');}));break;}
 case 'teach-new-scenario':dialog('Запомнить сценарий',input('title','Название сценария','Опыт '+((S.draft.scenarios?.length??0)+1))+`<label class="field"><span>Пояснение к шагу</span><textarea name="note" rows="3" maxlength="4000"></textarea></label>`,'Запомнить',async data=>{if(S.draft.kind==='html')await captureControls();mutate(m=>{m.scenarios??=[];m.scenarios.push({id:uid('scenario'),title:data.get('title'),note:data.get('note'),...(m.kind==='html'?{controls:structuredClone(m.initialControls??[])}:{parameters:Object.fromEntries(m.parameters.map(p=>[p.id,p.value])),camera:m.scene.camera?structuredClone(m.scene.camera):{x:(m.scene.minX+m.scene.maxX)/2,y:(m.scene.minY+m.scene.maxY)/2,zoom:1}})});});});break;
 case 'teach-scenario':{const scenario=S.draft.scenarios?.[Number(arg)];if(!scenario)throw new Error('Сценарий не найден');pushUndo();S.draft=applyScenario(S.draft,scenario);S.scenarioNote=scenario.note;S.comparison=null;changed();applySavedControls();render();break;}
 case 'teach-delete-scenario':mutate(m=>m.scenarios.splice(Number(arg),1));break;
 case 'teach-phase':S.lessonPhase=['prediction','experiment','explanation'].includes(arg)?arg:'prediction';render();break;
 case 'teach-measure':dialog('Измерения на сцене',`<p class="hint">Измерения используют координаты модели в метрах и градусах. Пробник учитывает все глобальные поля, включая скрытые карты.</p><div class="menu-actions">${['distance','angle','vectors','probe'].map((key,i)=>button('teach-new-measure:'+key,['Расстояние · линейка','Угол · транспортир','Угол между векторами','Пробник E, g, B'][i],'quiet full')).join('')}${(S.draft.measurements??[]).map((q,i)=>`<div class="scenario-edit"><span>${esc(q.label)}</span>${button('teach-edit-measure:'+i,'Изменить','quiet')}${button('teach-remove-measure:'+i,'Удалить','danger')}</div>`).join('')}</div>`);break;
 case 'teach-edit-measure':{const q=S.draft.measurements?.[Number(arg)];if(q)await handle('teach-new-measure:'+q.type+'~'+arg);break;}
 case 'teach-new-measure':{const [kind,index]=arg.split('~'),old=index!==undefined?S.draft.measurements?.[Number(index)]:null,label={distance:'Расстояние',angle:'Угол',vectors:'Угол векторов',probe:'Поле в точке'}[kind];if(!label)break;const fields=kind==='distance'?pick('a','Точка A',old?.a)+pick('b','Точка B',old?.b):kind==='angle'?pick('a','Точка A',old?.a)+pick('vertex','Вершина угла',old?.vertex)+pick('b','Точка B',old?.b):kind==='vectors'?pick('a','Начало вектора 1',old?.a)+pick('b','Конец вектора 1',old?.b)+pick('c','Начало вектора 2',old?.c)+pick('d','Конец вектора 2',old?.d):input('x','Координата x, м',old?.x??0,'number')+input('y','Координата y, м',old?.y??0,'number');dialog(label,input('label','Подпись',old?.label??label)+fields,old?'Сохранить изменения':'Добавить',async data=>mutate(m=>{m.measurements??=[];const q={id:old?.id??uid('measure'),type:kind,label:data.get('label')};for(const key of ['a','b','vertex','c','d'])if(data.has(key))q[key]=data.get(key);if(kind==='probe'){q.x=Number(data.get('x'));q.y=Number(data.get('y'));}if(old)m.measurements[Number(index)]=q;else m.measurements.push(q);}));break;}
 case 'teach-remove-measure':mutate(m=>m.measurements.splice(Number(arg),1));break;
 case 'teach-geometry':dialog('Геометрическая конструкция',`<p class="hint">Ограничения строят неподвижные точки по параметрам. Длины сохраняют масштаб, зависимую точку нельзя свободно перетаскивать.</p><div class="menu-actions">${[['circle','Точка на окружности'],['equal','Равная длина'],['parallel','Параллельный отрезок'],['perpendicular','Перпендикулярный отрезок']].map(([k,l])=>button('teach-new-geometry:'+k,l,'quiet full')).join('')}${(S.draft.geometry??[]).map((g,i)=>`<div class="scenario-edit"><span>${esc(g.type)} → ${esc(g.target)}</span>${button('teach-edit-geometry:'+i,'Изменить','quiet')}${button('teach-remove-geometry:'+i,'Удалить','danger')}</div>`).join('')}</div>`);break;
 case 'teach-edit-geometry':{const g=S.draft.geometry?.[Number(arg)];if(g)await handle('teach-new-geometry:'+g.type+'~'+arg);break;}
 case 'teach-new-geometry':{const [kind,index]=arg.split('~'),old=index!==undefined?S.draft.geometry?.[Number(index)]:null;dialog('Задать ограничение',pick('target','Зависимая точка',old?.target)+pick('center','Начало отрезка / центр',old?.center)+(kind!=='circle'?pick('a','Начало опорного отрезка',old?.a)+pick('b','Конец опорного отрезка',old?.b):'')+input('length','Длина, м · число или параметр',old?.length??2)+input('angle','Угол, ° · число или параметр',old?.angle??45)+`<p class="hint">Для окружности используются длина и угол. Для равной длины — длина опорного отрезка и заданный угол; для параллельности/перпендикулярности — заданная длина и направление опорного отрезка. Все выбранные точки должны иметь поведение «Неподвижный».</p>`,'Построить',async data=>mutate(m=>{m.geometry??=[];const g={id:old?.id??uid('geometry'),type:kind,target:data.get('target'),center:data.get('center'),a:data.get('a')??'',b:data.get('b')??'',length:data.get('length'),angle:data.get('angle')};if(old)m.geometry[Number(index)]=g;else m.geometry.push(g);}));break;}
 case 'teach-remove-geometry':mutate(m=>m.geometry.splice(Number(arg),1));break;
 case 'teach-slider':{const body=S.draft.bodies.find(b=>b.id===S.selection)??S.draft.bodies[0];if(!body)throw new Error('Сначала добавьте объект');dialog('Создать ползунок свойства',`<input name="body" type="hidden" value="${body.id}"><p>${esc(body.name)}</p><label class="field"><span>Свойство</span><select name="property">${Object.entries(bindingProperties).filter(([k])=>!(['x','y'].includes(k)&&S.draft.geometry?.some(g=>g.target===body.id))&&!S.draft.parameters.some(p=>p.binding?.body===body.id&&p.binding.property===k)).map(([k,v])=>`<option value="${k}">${esc(v[0])} · ${v[1]}</option>`).join('')}</select></label><p class="hint">Диапазон и подпись можно изменить в разделе «Параметры». Угол рисунка поворачивает значок; для геометрии используйте параметр в формуле ограничения.</p>`,'Создать ползунок',async data=>mutate(m=>{const property=data.get('property'),config=bindingProperties[property];if(!config)throw new Error('У всех свойств уже есть ползунки');const value=body[property]??0,min=Math.max(config[2],value===0?-1:Math.min(value*.25,value*2)),max=Math.min(config[3],value===0?1:Math.max(value*.25,value*2));let i=1;const used=new Set([...m.bodies,...m.parameters,...m.quantities,...m.connections,...m.fields].map(o=>o.id));while(used.has('control'+i))i++;m.parameters.push({id:'control'+i,label:(body.name+' · '+config[0]).slice(0,80),unit:config[1],value,min,max,binding:{body:body.id,property}});S.tab='parameters';}));break;}
 case 'teach-audit':{const job=S.auditJob=(S.auditJob??0)+1;S.running=false;dialog('Проверка модели',`<p id="audit-progress" role="status">Проверяю расчёт и чувствительность к шагу…</p><div id="audit-results"></div>`);const draft=structuredClone(S.draft),report=await auditModel(draft,()=>new Promise(r=>setTimeout(r,0))),node=document.querySelector('#audit-results');if(node&&job===S.auditJob){document.querySelector('#audit-progress').textContent='Проверка текущего черновика · '+fmt(report.seconds)+' с';node.innerHTML=report.checks.map(c=>`<article class="audit-check ${c.status}"><strong>${{pass:'✓',warn:'!',fail:'×',info:'i'}[c.status]} ${esc(c.title)}</strong><p>${esc(c.detail)}</p></article>`).join('')+button('teach-invariant','Добавить проверку постоянной величины','quiet full');}break;}
 case 'teach-invariant':dialog('Проверяемая постоянная величина',input('label','Название','Полный импульс')+input('expression','Формула','0')+input('absolute','Абсолютный допуск',.000001,'number')+input('relative','Относительный допуск',.0001,'number')+`<p class="hint">Пример для замкнутой пары: b1_m*b1_vx+b2_m*b2_vx. При внешней силе импульс может изменяться физически правильно.</p><div class="menu-actions">${(S.draft.invariants??[]).map((q,i)=>`<div class="scenario-edit"><span>${esc(q.label)}</span>${button('teach-remove-invariant:'+i,'Удалить','danger')}</div>`).join('')}</div>`,'Добавить проверку',async data=>mutate(m=>{m.invariants??=[];m.invariants.push({id:uid('law'),label:data.get('label'),expression:data.get('expression'),absolute:Number(data.get('absolute')),relative:Number(data.get('relative'))});}));break;
 case 'teach-remove-invariant':mutate(m=>m.invariants.splice(Number(arg),1));break;
 case 'teach-versions':{if(!S.record)throw new Error('Сначала сохраните модель');const id=S.record.id;const versions=await api({action:'versions',id});dialog('История сохранений',`<p class="hint">Хранятся последние 30 предыдущих версий. История начинает накапливаться после этого обновления. Открытие версии создаёт черновик; затем его можно сохранить или сделать копию.</p><div class="menu-actions">${versions.map(v=>`<article class="version-row"><strong>Версия ${v.revision}${v.current?' · текущая':''}</strong><span>${esc(new Date(v.updatedAt).toLocaleString('ru-RU'))} · ${esc(v.title)}</span>${button('teach-version:'+v.revision,'Открыть в редакторе','quiet')}</article>`).join('')}</div>`);break;}
 case 'teach-version':{const record=await api({action:'version',id:S.record.id,revision:Number(arg)});pushUndo();S.draft=structuredClone(record.spec);S.comparison=null;S.selection=S.draft.bodies[0]?.id??null;S.tab=S.draft.kind==='html'?'details':'settings';S.previewHTML=null;S.previewUrl=null;changed();applySavedControls();render();h.closeDialog();toast('Версия открыта как черновик. Текущая сохранённая версия остаётся в каталоге.');break;}
 case 'teach-compare':{if(!S.draft.parameters.length)throw new Error('Добавьте параметр или создайте ползунок свойства для второго опыта');const model=S.comparison?.model??S.draft;dialog('Сравнение двух опытов',`<p class="hint">Опыт A использует текущие параметры, B — значения ниже. Оба начинают с t = 0, используют общие оси и время. Сдвиг и масштаб плоскости общие.</p>${model.parameters.map(p=>input(p.id,p.label+' · '+p.unit,p.value,'number')).join('')}`,'Сравнить',async data=>{const m=structuredClone(S.draft);for(const p of m.parameters)p.value=Number(data.get(p.id));applyBindings(m);validatePhysics(validateModel(m));S.comparison={model:m,sim:initialState(m),history:[]};h.resetSimulation();S.comparison.history=[structuredClone(S.comparison.sim)];render();});break;}
 case 'teach-label-reset':mutate(m=>{const b=m.bodies.find(b=>b.id===S.selection);if(b)delete b.labelOffset;});break;
 case 'teach-unbind':mutate(m=>{const p=m.parameters.find(p=>p.id===arg);if(p)delete p.binding;});break;
 case 'teach-stop-compare':S.comparison=null;render();break;
 default:return false;
 }return true;}
 return {handle};
}
export function comparisonStep(S,h){const nextA=step(S.draft,S.sim,h);if(!S.comparison){S.sim=nextA;return;}const B=S.comparison;B.model.scene=structuredClone(S.draft.scene);const nextB=step(B.model,B.sim,h);S.sim=nextA;B.sim=nextB;if(!B.history.length||B.sim.t-B.history.at(-1).t>=Math.max(.025,S.draft.duration/1400)){B.history.push(structuredClone(B.sim));if(B.history.length>1600)B.history.shift();}}
export function comparisonDraw(S){const target=document.querySelector('#comparison-scene');if(!target||!S.comparison)return;const B=S.comparison;B.model.scene=structuredClone(S.draft.scene);target.innerHTML=sceneSVG(S.present&&S.draft.assignment?.hideResults&&(S.lessonPhase??'prediction')==='prediction'?{...B.model,measurements:[]}:B.model,B.sim,B.history).replace(/id="([^"]+)"/g,'id="compare-$1"').replace(/url\(#([^)]+)\)/g,'url(#compare-$1)');const values=document.querySelector('#comparison-values');const c=context(B.model,B.sim);if(values){const a=context(S.draft,S.sim);values.innerHTML=[[S.draft,a,'Опыт A'],[B.model,c,'Опыт B']].map(([model,scope,title])=>`<section><b>${title}</b>${model.quantities.map(q=>`<span>${esc(q.label)}: <strong>${fmt(scope[q.id])} ${esc(q.unit)}</strong></span>`).join('')}</section>`).join('');}const graphs=document.querySelector('#comparison-graphs');if(graphs)graphs.innerHTML=S.draft.graphs.map((g,i)=>{let scale=g;if(g.autoScale!==false){const values=[];for(const [m,history]of [[S.draft,S.history],[B.model,B.history]])for(const s of history){try{const v=evaluate(g.expression,context(m,s));if(Number.isFinite(v))values.push(v);}catch{}}const lo=values.length?Math.min(...values):0,hi=values.length?Math.max(...values):1,pad=hi>lo?(hi-lo)*.12:Math.max(Math.abs(lo)*.12,1e-9);scale={...g,autoScale:false,minY:lo-pad,maxY:hi+pad};}return `<div class="comparison-graph"><strong>${esc(g.label)} · общая шкала</strong><div><section><b>Опыт A</b>${graphSVG(S.draft,S.history,scale,i).replaceAll('graphClip','AgraphClip')}</section><section><b>Опыт B</b>${graphSVG(B.model,B.history,scale,i).replaceAll('graphClip','BgraphClip')}</section></div></div>`;}).join('');}
export function measurementCards(m,s){let c;try{c=context(m,s);}catch{return '';}return (m.measurements??[]).map(q=>{try{const v=measure(m,s,q,c);return `<div class="quantity"><span>${esc(q.label)}</span>${q.type==='probe'?`<strong>E = (${fmt(v.ex)}; ${fmt(v.ey)}) Н/Кл</strong><strong>g = (${fmt(v.gx)}; ${fmt(v.gy)}) м/с²</strong><strong>Bz = ${fmt(v.bz)} Тл</strong><small>φ = ${fmt(v.phi)} В · Φg = ${fmt(v.gravityPotential)} Дж/кг</small>`:`<strong>${fmt(v.value)} <small>${v.unit}</small></strong>`}</div>`;}catch(e){return `<div class="quantity"><span>${esc(q.label)}</span><small>${esc(e.message)}</small></div>`;}}).join('');}
