// Generated by tools/build-theme.mjs
try{const saved=localStorage.getItem("model-studio-theme");document.documentElement.dataset.theme=["light","dark","black","midnight","forest","sepia"].includes(saved)?saved:matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light";}catch{document.documentElement.dataset.theme="light";}
